### ISSUE TITLE
Feature Request: Only run when needed

### ISSUE THREAD

**Issue by bodograumann** [intermezzio/weffe#12]
Currently, the script always activates the webcam the whole time and uses processing resources.
Is it possible to pause the processing, while the output video device is not used?
Or maybe even automatically start the script when a process opens the device and exit afterwards.

**Comment by intermezzio** [comment]
That's a good idea. At this point I don't know if v4l2 supports streaming to a webcam on demand like that. At the very least, the virtual webcam doesn't stream data unless this script is run, and the script can be started or stopped whenever you want. If you have any ideas for how to implement this, or if you want to add this feature, any thoughts in this issue or a pull request would be much appreciated.

**Comment by bodograumann** [comment]
This is an approach using inotifywait. I need to see how well it works and how robust it is though.

```sh
#!/usr/bin/env sh

set -e

cleanup() {
  if [ -n "$pid" ]
  then
    kill "$pid"
  fi
}

while true
do
  printf "Waiting for camera to be opened...\n"
  inotifywait -qq -e open /dev/video7
  weffe -B portrait &
  pid=$!
  inotifywait -qq -e close /dev/video7
  kill $pid
  pid=""
done
```

**Comment by intermezzio** [comment]
This is a clever solution, thanks for sharing it with me. It didn't seem to work when I tried it locally (maybe it's because filestreams aren't treated the same way as files) but this is a good general structure for how something like that would work. I couldn't find a way to get inotifywait to follow the filestream `/dev/video7` but I've found [this solution with lsmod](https://unix.stackexchange.com/questions/344454/how-to-know-if-my-webcam-is-used-or-not#344463) and another implementation [here](https://github.com/jboero/livewebcam/blob/4a07badaa68fb394bb5537b104b0f337b45d0886/livewebcam#L41) which may be able to be swapped in for inotifywait. The only downside is that this command would have to be run periodically as it checks if the webcam is on as opposed to asynchronously waiting for the webcam to turn on. It's still a performance improvement over keeping it on at all times though.

**Comment by bodograumann** [comment]
Curious. I was at least able to correctly detect the `open` event on `/dev/video7`. Closing was not as reliable. Probably because some timing issues.
Also I have the problem, that the actual ffmpeg call is nested in subprocesses and the `kill` will not stop it. I tried different solutions with `pkill -P $$` and `setsid`, but haven’t get found a working solution. Directly putting the logic in the main script would of course work around that problem.

The `lsmod` approach seems interesting as well.
Though it cannot detect when a process is trying to open `/dev/video7` and failing because we are not writing any data to it yet. The usage count of the kernel module will stay at 0. Only opening of the actual camera can be detected with it. Not sure if that might be useful.
For detecting the end of camera usage, this might work though:
```sh
baseUsers=$(mod_users v4l2loopback)
while true
do
  sleep 1
  users=$(mod_users v4l2loopback)
  if [ "$baseUsers" -gt "$users" ]
  then
    break
  elif [ "$baseUsers" -lt "$users" ]
  then
    baseUsers=$users
  fi
done
```

**Comment by bodograumann** [comment]
Another thing we could do is always outputting a minimal placeholder (e.g. static image), which would probably consume very few resources.

**Comment by intermezzio** [comment]
It turns out inotifywait works, I was just fiddling with other v4l2 settings at the same time so it didn't work. I've implemented the inotifywait solution in a pull request I'm attaching, and the relevant code is [here](https://github.com/intermezzio/weffe/blob/9ab71215712e7b36255b10e9fe70726952652ef8/weffe#L218):
```sh
if [[ $persistent == false ]]
	while true
	do
		printf "Waiting for camera to be opened...\n"
		sh -c "$alt_ffmpegstr" &
		pid=$!
		sleep 0.1 # wait for camera to stop thinking it's still open
		inotifywait -qq -e open /dev/video$output
		printf "Camera opened\n"
		kill $pid
		sh -c "$ffmpegstr" &
		pid=$!
		printf "Waiting for close\n"
		inotifywait -qq -e close /dev/video$output
		printf "Closed, revert to simple film\n"
		kill $pid &
		tail --pid=$! -f /dev/null
	done
else
	sh -c "$ffmpegstr"
fi
```

I still have to run some tests to make sure this code works in all conditions before merging the pull request.

**Comment by intermezzio** [comment]
If you would like to test this yourself, you can clone the issue 12 branch and run `./weffe` locally from within the repository. You're welcome to add more, make changes, or otherwise let me know your thoughts on this change. Currently, I'm planning to make this the new default way weffe runs with an option `-P` (persistent) for making weffe run all the time, as it does now.

**Comment by bodograumann** [comment]
I will definitely try it out.
Note that this means we have to add inotify-tools as a dependency.

**Comment by bodograumann** [comment]
It already works pretty good.
Two things I noticed:
- The alternative stream actually uses more cpu resources than the normal camera stream. Maybe the framerate needs to be limited?
- Sometimes the camera is active even though it is not being used. I think the problem is not, that the closing was not detected, but that the camera was stopped and than started again, even though nothing was actually reading the stream. Not sure where that spurious open event comes from. Maybe from our ffmpeg itself, which opens it to write?

**Comment by intermezzio** [comment]
* In the alternative stream I have it generate a background with a single color, I'll see if having it feed an image to the virtual camera is more efficient, although it will need to be resized to fit the resolution. Is the alternative stream using more resources even when filters are added (e.g. blur, etc?)
* I think this is because the camera itself doesn't "turn off" until a fraction of a second after the ffmpeg script stops, so when inotifywait runs it still thinks it's open. I can increase the sleep time to see if that fixes it, but it works on my end.

**Comment by bodograumann** [comment]
The alternative stream is basically using one whole core.
The actual stream has blur and an overlay, but doesn’t need as much resources.

I’ll keep an eye the close issue. Maybe another idea would be to have a counter that listens to every open and close event. Then the difference between the counts tells us whether the device is opened or closed.

**Comment by bodograumann** [comment]
Today after coming out of suspend, weffe was caught in loop of opening and closing the camera.
The following output repeated:
```
Camera opened
Waiting for close
Closed, revert to simple film
Waiting for camera to be opened...
./static/blur_portrait.png: Immediate exit requested
```

I have encountered that `Immediate exit requested` before, but not sure what it means exactly.

**Comment by bodograumann** [comment]
One important thing to note, is that ffmpeg itself generates an `open` event when started and `close_write`, `close` events when stopped. These might trip us up.

Here is a way to observe the events and their timings:
```
inotifywait -me open,close /dev/video7 | while read line; do echo $(date +%T.%N) $line; done
```

Or to count the number of reading processes:
```
> inotifywait -q -me open,close /dev/video7 | awk 'BEGIN { count = 0 } /OPEN/ { count++ } /CLOSE/ { count-- } { print count " [" $0 "]" }'
1 [/dev/video7 OPEN ]
2 [/dev/video7 OPEN ]
1 [/dev/video7 CLOSE_WRITE,CLOSE ]
2 [/dev/video7 OPEN ]
1 [/dev/video7 CLOSE_WRITE,CLOSE ]
0 [/dev/video7 CLOSE_WRITE,CLOSE ]
1 [/dev/video7 OPEN ]
0 [/dev/video7 CLOSE_WRITE,CLOSE ]
```

What you can see above is:
```
1 weffe starts writing placeholder
2 video call client opens dev for reading
1 weffe stops writing placeholder
2 weffe starts passing through from camera
1 video call client closes dev
0 weffe stops passing through from camera
1 weffe starts writing placeholder
0 weffe stops writing placeholder
```

**Comment by bodograumann** [comment]
This version should avoid any race conditions and also handle the case, where a client quickly opens and closes the device (state "ABORT STREAM").

```sh
if [[ $persistent != false ]]
then
	sh -c "$ffmpegstr"
	exit
fi

set +e
read -r -d '' state_machine <<'AWK'
	BEGIN {
		state = "START_IDLE"
		print "IDLE"
	}
	/OPEN/ {
		if (state == "START_IDLE") {
			state = "IDLE"
		} else if (state == "IDLE") {
			state = "STOP_IDLE"
			print "STOP"
		} else if (state == "START_STREAM") {
			state = "STREAM"
		} else if (state == "ABORT_STREAM") {
			state = "STOP_STREAM"
			print "STOP"
		} else {
			print "Unexpected OPEN event in state " state
			next
		}
	}
	/CLOSE/ {
		if (state == "IDLE") {
			exit
		} else if (state == "STOP_IDLE") {
			state = "START_STREAM"
			print "STREAM"
		} else if (state == "START_STREAM") {
			state = "ABORT_STREAM"
		} else if (state == "STREAM") {
			state = "STOP_STREAM"
			print "STOP"
		} else if (state == "STOP_STREAM") {
			state = "START_IDLE"
			print "IDLE"
		} else {
			print "Unexpected CLOSE event in state " state
			next
		}
	}
	{
		print "<" state ">"
	}
AWK
set -e

inotifywait -q -me open,close /dev/video$output \
	| stdbuf -oL awk "$state_machine" \
	| while read -r action
		do
			echo "$action"
			if [ "$action" = "IDLE" ]
			then
				sh -c "$alt_ffmpegstr" &
				pid=$!
			elif [ "$action" = "STREAM" ]
			then
				sh -c "$ffmpegstr" &
				pid=$!
			elif [ "$action" = "STOP" ]
			then
				kill $pid &
			fi
		done
```

**Comment by intermezzio** [comment]
After changing a couple of the strings to make the code run, I've pushed the changes [here](https://github.com/intermezzio/weffe/blob/issue-12-only-run-when-needed/weffe#L218). At first glance, this seems to be a robust solution that works, but I'll need to test this more before merging to the main branch. Does this work on your computer?

**Comment by bodograumann** [comment]
Yes, that seems to work nicely.

I have also found that using the `realtime` filter in idle mode reduces cpu usage massively:
```
alt_filterstr="color=c=#543c00:s=$outputsize,realtime,format=yuv420p[v]"
```

One problem I’m still seeing, is that I get stuck in idle mode. This happens after suspending and awaking, but also when switching to the real camera during a call and then switching back.
When trying the latter I see `Unexpected OPEN event in state STREAM` and `Unexpected CLOSE event in state ABORT_STREAM`. Until now I mainly considered one application being able to read a stream at the same time, but maybe that is not actually true. E.g. I see these events:
```
15:20:30.308292186 1 [/dev/video7 OPEN ]
15:20:38.928135085 2 [/dev/video7 OPEN ]
15:20:38.949104601 1 [/dev/video7 CLOSE_WRITE,CLOSE ]
15:20:40.155463937 2 [/dev/video7 OPEN ]
15:20:49.343486008 3 [/dev/video7 OPEN ]
15:20:49.346570391 2 [/dev/video7 CLOSE_NOWRITE,CLOSE ]
15:20:49.348025400 3 [/dev/video7 OPEN ]
15:20:49.350128565 2 [/dev/video7 CLOSE_NOWRITE,CLOSE ]
15:20:49.352776384 1 [/dev/video7 CLOSE_WRITE,CLOSE ]
15:20:49.360602700 0 [/dev/video7 CLOSE_WRITE,CLOSE ]
```

Not sure how to best handle this situation yet.

**Comment by intermezzio** [comment]
Yes, a webcam technically can stream to multiple outputs - in this case we can use lsmod to count how many streams are open when the stream is closed, or we can have an integer counter when the script starts and keep track of open streams.

**Comment by bodograumann** [comment]
Adding a counter seems to mitigate any problems when switching between real and modified camera:
```awk
state_machine='
	BEGIN {
		state = "START_IDLE"
		count = 0
		print "IDLE"
	}
	/OPEN/ {
		count++
		if (state == "START_IDLE") {
			state = "IDLE"
		} else if (state == "IDLE") {
			state = "STOP_IDLE"
			print "STOP"
		} else if (state == "START_STREAM") {
			state = "STREAM"
		} else if (state == "ABORT_STREAM") {
			state = "STOP_STREAM"
			print "STOP"
		} else if (state == "STOP_STREAM") {
			state = "RESTART_STREAM"
		} else if (state == "STOP_IDLE" || state == "STREAM" || state == "RESTART_STREAM" ) {
			# Waiting for previous instance to close to switch streams.
		} else {
			print "Unexpected OPEN event in state " state
			next
		}
	}
	/CLOSE/ {
		count--
		if (state == "IDLE") {
			exit
		} else if (state == "STOP_IDLE" || state == "RESTART_STREAM") {
			state = "START_STREAM"
			print "STREAM"
		} else if (state == "START_STREAM") {
			if (count == 0) {
				state = "ABORT_STREAM"
			}
		} else if (state == "STREAM") {
			if (count == 1) {
				state = "STOP_STREAM"
				print "STOP"
			}
		} else if (state == "STOP_STREAM") {
			state = "START_IDLE"
			print "IDLE"
		} else {
			print "Unexpected CLOSE event in state " state
			next
		}
	}
	{
		print "<" state " @ " count ">"
	}'
```

I have still no idea though, why nothing happens anymore after resuming from suspend.

**Comment by intermezzio** [comment]
When you resume from suspend, can you <kbd>Ctrl</kbd>+<kbd>C</kbd> out of it and restart the script? If so I may add this feature the way it is since I don't have the bandwidth to add a lot of features right now.

**Comment by bodograumann** [comment]
Yes, that is what I usually do.

**Comment by intermezzio** [comment]
I've updated the branch with the change, and it seems to work for me but it still prints that it's going to start and stop the stream about once a second, although the light on my webcam doesn't turn on indicating that it isn't actually accessing it. The camera seems to turn on when it needs to but the print statements seem concerning. Can you take a look at it and tell me what you think? I just tested it with `./weffe -B square`

**Comment by bodograumann** [comment]
Still works fine for me with the latest version (using ms teams).
Could you do
```
./weffe -B portrait | while read line; do echo $(date +%T.%N) $line; done
```
and post what the sequence of events is?

**Comment by intermezzio** [comment]
This is the output in my terminal after that:
```
08:33:26.891095043 IDLE
08:33:27.008004336 <IDLE @ 1>
08:33:27.230162169 STOP
08:33:27.233372854 <STOP_IDLE @ 2>
08:33:27.236308952 STREAM
08:33:27.239307989 <START_STREAM @ 1>
08:33:27.241860360 <STREAM @ 2>
08:33:27.244325927 STOP
08:33:27.246943252 <STOP_STREAM @ 1>
08:33:27.249923663 <RESTART_STREAM @ 2>
08:33:27.252542174 STREAM
08:33:27.255309093 <START_STREAM @ 1>
08:33:27.257903374 <STREAM @ 2>
08:33:27.260450920 STOP
08:33:27.262852182 <STOP_STREAM @ 1>
08:33:27.265445110 IDLE
08:33:27.268295400 <START_IDLE @ 0>
08:33:27.367750501 <IDLE @ 1>
08:33:30.350413794 STOP
08:33:30.353265692 <STOP_IDLE @ 2>
08:33:30.355902211 STREAM
08:33:30.358406397 <START_STREAM @ 1>
08:33:30.361213864 <STREAM @ 2>
08:33:30.364024821 STOP
08:33:30.366866317 <STOP_STREAM @ 1>
08:33:30.369545311 <RESTART_STREAM @ 2>
08:33:30.372116395 STREAM
08:33:30.374663150 <START_STREAM @ 1>
08:33:30.377265104 <STREAM @ 2>
08:33:30.380174553 STOP
08:33:30.382861291 <STOP_STREAM @ 1>
08:33:30.385605644 IDLE
08:33:30.388250444 <START_IDLE @ 0>
08:33:30.486199743 <IDLE @ 1>
08:33:33.470563534 STOP
```
It seems to repeat this every couple of seconds. The webcam was not turned on here and the light on my webcam didn't turn on to indicate that it's in use.

**Comment by bodograumann** [comment]
Given that your webcam is not indicating activity, we can assume that the `STREAM` is not initialized properly before it is canceled again by the `STOP` command.
Usually we expect a `CLOSE` and an `OPEN` event after issuing `STREAM`, indicating that the idle stream was closed and the webcam stream was started. Here though, these events seem not to be comming from our own actions, but from the consumer app. First it opens the idle stream and before we can close it and start the real stream, it stops and starts reading again.

Not sure how to best handle this. It would be interesting to see what OPEN and CLOSE events are emited on your system when running a persistent stream. At least to confirm this analysis.

**Comment by intermezzio** [comment]
After looking at the problem a little closer, it appears that on my computer, the inotifywait command states that there's an open and a close_nowrite event every couple of seconds, and when an actual application opens it there's an open event (with a close_write event when it stops). This seems to lead to a lot of print statements, and the video and alt feed streams alternate back and forth really quickly when a video device is opened.

**Comment by intermezzio** [comment]
Here's what is printed when I stream a video:
```
<START_STREAM @ 1>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
<STREAM @ 3>
<STREAM @ 2>
STOP
<STOP_STREAM @ 1>
IDLE
<START_IDLE @ 0>
<IDLE @ 1>
STOP
<STOP_IDLE @ 2>
STREAM
<START_STREAM @ 1>
```

**Comment by bodograumann** [comment]
Could be that some application is polling the video device for availability. This of course collides with approach of using the open event as a signal to start streaming.
When already streaming that just cycles the count between 2 and 3, which is fine. (Debug output can be reduced further anyway when we are more confident.)
When we are idling, we could maybe have some intermediate state “waiting if serious” and only go to STOP_IDLE if the reader does not close the stream after few miliseconds.

**Comment by intermezzio** [comment]
It seems peculiar since when I ran the code without the counter it worked but with the counter it doesn't. Given this, I'm planning to take the code without the counter and clean up some print statements and merge it as an optional parameter (adding inotifywait as an optional dependency) to create a v1.1 release. This issue can stay open as we look into ways to make the feature more robust even when the webcam is polled.

**Comment by intermezzio** [comment]
Actually it turns out the code with the counter works and I'm pretty sure the blinking came from multiple ffmpeg tasks running in parallel. The only problem seems to arise when the script is called and something (e.g. zoom) is already attempting to stream from the webcam, in which case it thinks it's starting at idle when it really isn't. With the local changes I've made there's an easy workaround: if the webcam is already on when the script is on, turn off the webcam once and turn it back on and it'll work fine. However, I think defining the initial state with lsmod would be a robust way to determine whether to start streaming or not. By any chance can you fix this code I've written for it? I'm not as familiar with awk programming but here's the idea:

```awk
BEGIN {
v4l2 = system("lsmod | grep \"^v4l2loopback\"")
count = 0
if (count == 0) {
	state = "START_IDLE"
	print "IDLE"
} else {
	state = "START_STREAM"
	print "STREAM"
}
}
```

All I need to fix is lines 2-3, where the variable v4l2 gets the line "v4l2loopback           57344  1" and the third value (1 in this case) needs to be assigned to count.

**Comment by bodograumann** [comment]
Ah yes, that is a problem I also faced some times. Good to hear that it is not something deeper.
Not sure initializing the count this way will always be reliable though. Will have to think about it some more.

For now here is what you requested:
`lsmod` is only a formatter for /proc/modules, so I think we can use that directly. A more low-level approach to read the count would be:

```sh
while read -r mod _ usage _
do
    if [ "$mod" = "v4l2loopback" ]
    then
        export INITIAL_COUNT="$usage"
        break
    fi
done < /proc/modules
```

Then the awk script can access the variable:
```awk
BEGIN {
    count = ENVIRON["INITIAL_COUNT"]
}
```

Some other, shorter but maybe not clearer variants to extract the count inside awk:
- `"sed -n 's/^v4l2loopback [^ ]\+ \([0-9]\+\).*/\1/p' /proc/modules" | getline count`
- `"grep '^v4l2loopback ' /proc/modules | cut -d' ' -f3" | getline count`
- `"grep '^v4l2loopback ' /proc/modules" | getline out; split(out, v4l2, " "); count = v4l2[3]`

When using `system` you cannot get the output of the command. That’s why I had to switch to `getline` here.

**Comment by intermezzio** [comment]
Thanks for the information on how to get the count from `/proc/modules`. After considering the usability of this, I realized that if weffe is run in multiple locations, e.g. if there are two virtual webcams, this output is only taking account the total streams inputting and outputting to any virtual webcam, so it won't properly get an initial count. If it were just one, it would be accurate (as there is no input stream before weffe is run so it only counts output streams). Given this, I think it's best to assume that the count is zero unless there's a way to get the number of output streams for a specific virtual webcam.
```awk
state_machine='
	BEGIN {
		state = "START_IDLE"
		count = 0
		print "IDLE"
	}
	/OPEN/ {
		count++
		if (state == "START_IDLE") {
			state = "IDLE"
		} else if (state == "IDLE") {
			state = "STOP_IDLE"
			print "STOP"
		} else if (state == "START_STREAM") {
			state = "STREAM"
		} else if (state == "ABORT_STREAM") {
			state = "STOP_STREAM"
			print "STOP"
		} else if (state == "STOP_STREAM") {
			state = "RESTART_STREAM"
		} else if (state == "STOP_IDLE" || state == "STREAM" || state == "RESTART_STREAM" ) {
			# Waiting for previous instance to close to switch streams.
		} else {
			print "Unexpected OPEN event in state " state
			next
		}
	}
	/CLOSE/ {
		count--
		if (state == "IDLE") {
			next
		} else if (state == "STOP_IDLE" || state == "RESTART_STREAM") {
			state = "START_STREAM"
			print "STREAM"
		} else if (state == "START_STREAM") {
			if (count == 0) {
				state = "ABORT_STREAM"
			}
		} else if (state == "STREAM") {
			if (count == 1) {
				state = "STOP_STREAM"
				print "STOP"
			}
		} else if (state == "STOP_STREAM") {
			state = "START_IDLE"
			print "IDLE"
		} else {
			print "Unexpected CLOSE event in state " state
			next
		}
	}
	{
		print "<" state " @ " count ">"
	}'
```

**Comment by intermezzio** [comment]
On another note, I found the actual cause of the webcam probing problem. It turns out whenever Discord is open it periodically checks every available webcam for a very short amount of time and immediately closes the webcam. Since a non-negligible amount of people use this (and a bunch of other tools I'm not testing for probe webcams too), it may be a good idea to create a sort of timeout to only turn the webcam on if it's been at least, say, 0.1 or 0.5 seconds since the open event. There should be some time function in awk that allows this to work and a new state (e.g. STREAM_CHECK) which is activated before START_STREAM and is cancelled if a close event takes place soon enough. What are your thoughts on this modification to the feature?

**Comment by bodograumann** [comment]
Yes, this timeout feature is exactly what I imagined.
Just haven’t yet looked into implementing it.
Maybe remember the system time of the last state change and calculate how much time has passed?

**Comment by intermezzio** [comment]
Due to time constraints I'll add a `-M` (monitor) flag for this feature and make `inotify-tools` an optional dependency, which I'm merging in a `v1.1` release. I'll keep this issue open for further development of the feature to hopefully fix the probing error and make it high enough fidelity to use as a default option.
